# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class InitLabels(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, initial: float=None, target: float=None):  # noqa: E501
        """InitLabels - a model defined in Swagger

        :param initial: The initial of this InitLabels.  # noqa: E501
        :type initial: float
        :param target: The target of this InitLabels.  # noqa: E501
        :type target: float
        """
        self.swagger_types = {
            'initial': float,
            'target': float
        }

        self.attribute_map = {
            'initial': 'initial',
            'target': 'target'
        }

        self._initial = initial
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'InitLabels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The initLabels of this InitLabels.  # noqa: E501
        :rtype: InitLabels
        """
        return util.deserialize_model(dikt, cls)

    @property
    def initial(self) -> float:
        """Gets the initial of this InitLabels.


        :return: The initial of this InitLabels.
        :rtype: float
        """
        return self._initial

    @initial.setter
    def initial(self, initial: float):
        """Sets the initial of this InitLabels.


        :param initial: The initial of this InitLabels.
        :type initial: float
        """

        self._initial = initial

    @property
    def target(self) -> float:
        """Gets the target of this InitLabels.


        :return: The target of this InitLabels.
        :rtype: float
        """
        return self._target

    @target.setter
    def target(self, target: float):
        """Sets the target of this InitLabels.


        :param target: The target of this InitLabels.
        :type target: float
        """

        self._target = target
